title: Radmila Mandzhieva # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data & IT-analyst | Technical Writer & Case Developer
  <br><br>
  Open for new opportunities as Data Analyst / Data Scientist || Tech Writer @ Yandex (current) & ex-(Data & IT)Analyst @ Changellenge >>
  <br><br>
  <a href="https://www.linkedin.com/in/manrad/">My LinkedIn Profile</a> 
  <br><br>
  <a href="https://medium.com/@radmilamandzhi">My Medium page</a> 
  <br><br>
  <a href="https://github.com/simonyelisey/Shift-Enter/blob/main/Problems.docx.pdf">An example of the task I wrote for the Shift + Enter virtual internship</a> 
  <br><br>
  <a href="https://roasted-iron-2d2.notion.site/Hack-Change-2022-by-Changellenge-7b2f2c3d00774ec8b8f786bbe505b92a">One of the Notion files I created</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
